apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - certmanager-role.yaml
  - coredns-role.yaml
  - dex-auth-role.yaml
  - fluent-bit-role.yaml
  - kyverno-role.yaml
  - node-feature-discovery-role.yaml
  - policy-reporter-role.yaml
  - screenapi-nginx-role.yaml
  - vault-operator-role.yaml
  - vector-role.yaml
  - velero-role.yaml
  - victoria-metrics-operator-role.yaml
  - x509-role.yaml
